# Read the Docs configuration file
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html

# Install the project and its dependencies
python:
  install:
    # Install documentation dependencies
    - requirements: docs/requirements.txt
    # Install the project itself (needed for autodoc to import modules)
    - method: pip
      path: .
      extra_requirements:
        - dev
